Feature/docker ocpi adjustments
citrineos/citrineos-ocpi pull request #127
Opened 2024-07-31 21:04 UTC by elliot-sabitov

feat: moving latest core with ocpi server implementation into ocpi /Server and adjusting paths, npm run commands, docker file, etc. to use locally referenced `core` from within `ocpi`
feat: renaming OcpiServerConfig to ServerConfig, breaking it down into multiple files and creating some additional models to better match config with core, supporting defaults, to ensure a cleaner integration while allowing OCPI to layer additional configs.
chore: created npm run clear cache and enhancing npm run fresh to also clear cache after noticing issues after clearing local cache, clearing cache with fresh should make sure that any future issues are captured and resolved early.
chore: created npm run copy-assets, in a simple helper script to ensure that it can run properly across platforms. Triggering copy-assets in postbuild to ensure that assets folder is copied over otherwise we face errors
chore: adjusting config values that reference a file in the assets directory to reference relatively to the asset files to ensure that they can be loaded
chore: bringing in missing dependencies and resolving build issues
chore: removing core dependencies from modules that import ocpi-base since ocpi-base already import core dependencies.
chore: for now copied most of /Server from core into ocpi because it closest matched what need to be able to run core with ocpi. This is a temporary solution and there will be a fast follow to instead move this to the demo repo.

2024-07-31 21:17 UTC, elliot-sabitov commented on 00_Base/src/config/sub/ServerConfigUtilMessageBrokerAmqp.ts
> +  constructor() {
Please note: constructors in these `config` related classes are intended only to be defaults giving us the option to be able to eliminate the `local` version of the config which can be chosen as the "default"

2024-08-02 16:21 UTC, thanaParis requested changes
Please re-add Server. There should be a way to run core + ocpi 2.2.1 from this repo.
There are a lot of changes in this PR. Please break it down into separate PRs where possible.

2024-08-05 16:36 UTC, elliot-sabitov commented
Broke this original PR down into smaller PRs:
- https://github.com/citrineos/citrineos-ocpi/pull/130
- https://github.com/citrineos/citrineos-ocpi/pull/129
- https://github.com/citrineos/citrineos-ocpi/pull/131

2024-08-15 20:43 UTC, yuvenus approved these changes

2024-08-16 17:21 UTC, thanaParis approved these changes
Approved!

2024-08-16 17:22 UTC, merged